spring:
  cache:
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 111
    url: jdbc:mysql://192.168.147.131:3306/encache-demo?characterEncoding=UTF-8

mybatis:
  type-aliases-package: com.csw.encachedemo.entity
  mapper-locations: classpath:com/csw/encachedemo/mapper/*Mapper.xml
# 日志
logging:
  level:
    com.csw.encachedemo: debug